// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.advanceFinalizedFrontierStmt, err = db.PrepareContext(ctx, advanceFinalizedFrontier); err != nil {
		return nil, fmt.Errorf("error preparing query AdvanceFinalizedFrontier: %w", err)
	}
	if q.applyLogEditStmt, err = db.PrepareContext(ctx, applyLogEdit); err != nil {
		return nil, fmt.Errorf("error preparing query ApplyLogEdit: %w", err)
	}
	if q.getCombinedABIStmt, err = db.PrepareContext(ctx, getCombinedABI); err != nil {
		return nil, fmt.Errorf("error preparing query GetCombinedABI: %w", err)
	}
	if q.getCursorStmt, err = db.PrepareContext(ctx, getCursor); err != nil {
		return nil, fmt.Errorf("error preparing query GetCursor: %w", err)
	}
	if q.selectLogsStmt, err = db.PrepareContext(ctx, selectLogs); err != nil {
		return nil, fmt.Errorf("error preparing query SelectLogs: %w", err)
	}
	if q.selectLogsWindowAscStmt, err = db.PrepareContext(ctx, selectLogsWindowAsc); err != nil {
		return nil, fmt.Errorf("error preparing query SelectLogsWindowAsc: %w", err)
	}
	if q.selectLogsWindowDescStmt, err = db.PrepareContext(ctx, selectLogsWindowDesc); err != nil {
		return nil, fmt.Errorf("error preparing query SelectLogsWindowDesc: %w", err)
	}
	if q.upsertStateStmt, err = db.PrepareContext(ctx, upsertState); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertState: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.advanceFinalizedFrontierStmt != nil {
		if cerr := q.advanceFinalizedFrontierStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing advanceFinalizedFrontierStmt: %w", cerr)
		}
	}
	if q.applyLogEditStmt != nil {
		if cerr := q.applyLogEditStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing applyLogEditStmt: %w", cerr)
		}
	}
	if q.getCombinedABIStmt != nil {
		if cerr := q.getCombinedABIStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCombinedABIStmt: %w", cerr)
		}
	}
	if q.getCursorStmt != nil {
		if cerr := q.getCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCursorStmt: %w", cerr)
		}
	}
	if q.selectLogsStmt != nil {
		if cerr := q.selectLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing selectLogsStmt: %w", cerr)
		}
	}
	if q.selectLogsWindowAscStmt != nil {
		if cerr := q.selectLogsWindowAscStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing selectLogsWindowAscStmt: %w", cerr)
		}
	}
	if q.selectLogsWindowDescStmt != nil {
		if cerr := q.selectLogsWindowDescStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing selectLogsWindowDescStmt: %w", cerr)
		}
	}
	if q.upsertStateStmt != nil {
		if cerr := q.upsertStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertStateStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	advanceFinalizedFrontierStmt *sql.Stmt
	applyLogEditStmt             *sql.Stmt
	getCombinedABIStmt           *sql.Stmt
	getCursorStmt                *sql.Stmt
	selectLogsStmt               *sql.Stmt
	selectLogsWindowAscStmt      *sql.Stmt
	selectLogsWindowDescStmt     *sql.Stmt
	upsertStateStmt              *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		advanceFinalizedFrontierStmt: q.advanceFinalizedFrontierStmt,
		applyLogEditStmt:             q.applyLogEditStmt,
		getCombinedABIStmt:           q.getCombinedABIStmt,
		getCursorStmt:                q.getCursorStmt,
		selectLogsStmt:               q.selectLogsStmt,
		selectLogsWindowAscStmt:      q.selectLogsWindowAscStmt,
		selectLogsWindowDescStmt:     q.selectLogsWindowDescStmt,
		upsertStateStmt:              q.upsertStateStmt,
	}
}
