// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/ethereum/go-ethereum/common"
)

type Log struct {
	TxHash         common.Hash    `json:"tx_hash"`
	TxIndex        uint64         `json:"tx_index"`
	LogIndex       uint64         `json:"log_index"`
	BlockNumber    uint64         `json:"block_number"`
	BlockHash      common.Hash    `json:"block_hash"`
	BlockTimestamp uint64         `json:"block_timestamp"`
	Address        common.Address `json:"address"`
	Topics         []byte         `json:"topics"`
	Data           []byte         `json:"data"`
	Tags           uint64         `json:"tags"`
}

type State struct {
	ID                int64  `json:"id"`
	FinalizedFrontier uint64 `json:"finalized_frontier"`
	CombinedAbi       string `json:"combined_abi"`
}
