// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/ethereum/go-ethereum/common"
)

const advanceFinalizedFrontier = `-- name: AdvanceFinalizedFrontier :exec
UPDATE state SET finalized_frontier = ?1
WHERE id = 1 AND ?1 >= finalized_frontier
`

func (q *Queries) AdvanceFinalizedFrontier(ctx context.Context, finalizedFrontier uint64) error {
	_, err := q.exec(ctx, q.advanceFinalizedFrontierStmt, advanceFinalizedFrontier, finalizedFrontier)
	return err
}

const applyLogEdit = `-- name: ApplyLogEdit :execrows
INSERT INTO log (
	tx_hash,
	tx_index,
	log_index,
	block_number,
	block_hash,
	block_timestamp,
	address,
	topics,
	data,
	tags
) SELECT
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7,
	?8,
	?9,

	?10
WHERE ?4 >= (SELECT finalized_frontier FROM state WHERE id = 1)
ON CONFLICT (block_hash, log_index) DO UPDATE SET tags = log.tags | excluded.tags
`

func (q *Queries) ApplyLogEdit(ctx context.Context, arg Log) (int64, error) {
	result, err := q.exec(ctx, q.applyLogEditStmt, applyLogEdit,
		arg.TxHash,
		arg.TxIndex,
		arg.LogIndex,
		arg.BlockNumber,
		arg.BlockHash,
		arg.BlockTimestamp,
		arg.Address,
		arg.Topics,
		arg.Data,
		arg.Tags,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCombinedABI = `-- name: GetCombinedABI :one
SELECT combined_abi FROM state WHERE id = 1
`

func (q *Queries) GetCombinedABI(ctx context.Context) (string, error) {
	row := q.queryRow(ctx, q.getCombinedABIStmt, getCombinedABI)
	var combined_abi string
	err := row.Scan(&combined_abi)
	return combined_abi, err
}

const getCursor = `-- name: GetCursor :one
SELECT finalized_frontier FROM state WHERE id = 1
`

func (q *Queries) GetCursor(ctx context.Context) (uint64, error) {
	row := q.queryRow(ctx, q.getCursorStmt, getCursor)
	var finalized_frontier uint64
	err := row.Scan(&finalized_frontier)
	return finalized_frontier, err
}

const selectLogs = `-- name: SelectLogs :many
SELECT tx_hash, tx_index, log_index, block_number, block_hash, block_timestamp, address, topics, data, tags FROM log
WHERE block_number BETWEEN ?1 AND ?2
ORDER BY block_number, log_index, block_hash
`

type SelectLogsParams struct {
	Lo uint64 `json:"lo"`
	Hi uint64 `json:"hi"`
}

func (q *Queries) SelectLogs(ctx context.Context, arg SelectLogsParams) ([]Log, error) {
	rows, err := q.query(ctx, q.selectLogsStmt, selectLogs, arg.Lo, arg.Hi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.TxHash,
			&i.TxIndex,
			&i.LogIndex,
			&i.BlockNumber,
			&i.BlockHash,
			&i.BlockTimestamp,
			&i.Address,
			&i.Topics,
			&i.Data,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLogsWindowAsc = `-- name: SelectLogsWindowAsc :many
SELECT tx_hash, tx_index, log_index, block_number, block_hash, block_timestamp, address, topics, data, tags FROM log
WHERE (block_number,log_index,block_hash) > (?1,?2,?3)
ORDER BY block_number ASC, log_index ASC, block_hash ASC
LIMIT ?4
`

type SelectLogsWindowAscParams struct {
	BlockNumber uint64      `json:"block_number"`
	LogIndex    uint64      `json:"log_index"`
	BlockHash   common.Hash `json:"block_hash"`
	Limit       int64       `json:"limit"`
}

func (q *Queries) SelectLogsWindowAsc(ctx context.Context, arg SelectLogsWindowAscParams) ([]Log, error) {
	rows, err := q.query(ctx, q.selectLogsWindowAscStmt, selectLogsWindowAsc,
		arg.BlockNumber,
		arg.LogIndex,
		arg.BlockHash,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.TxHash,
			&i.TxIndex,
			&i.LogIndex,
			&i.BlockNumber,
			&i.BlockHash,
			&i.BlockTimestamp,
			&i.Address,
			&i.Topics,
			&i.Data,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLogsWindowDesc = `-- name: SelectLogsWindowDesc :many
SELECT tx_hash, tx_index, log_index, block_number, block_hash, block_timestamp, address, topics, data, tags FROM log
WHERE (block_number,log_index,block_hash) < (?1,?2,?3)
ORDER BY block_number DESC, log_index DESC, block_hash DESC
LIMIT ?4
`

type SelectLogsWindowDescParams struct {
	BlockNumber uint64      `json:"block_number"`
	LogIndex    uint64      `json:"log_index"`
	BlockHash   common.Hash `json:"block_hash"`
	Limit       int64       `json:"limit"`
}

func (q *Queries) SelectLogsWindowDesc(ctx context.Context, arg SelectLogsWindowDescParams) ([]Log, error) {
	rows, err := q.query(ctx, q.selectLogsWindowDescStmt, selectLogsWindowDesc,
		arg.BlockNumber,
		arg.LogIndex,
		arg.BlockHash,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.TxHash,
			&i.TxIndex,
			&i.LogIndex,
			&i.BlockNumber,
			&i.BlockHash,
			&i.BlockTimestamp,
			&i.Address,
			&i.Topics,
			&i.Data,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertState = `-- name: UpsertState :exec
INSERT INTO state (id, finalized_frontier, combined_abi)
VALUES (1, ?1, ?2)
ON CONFLICT (id) DO NOTHING
`

type UpsertStateParams struct {
	Frontier    uint64 `json:"frontier"`
	CombinedAbi string `json:"combined_abi"`
}

func (q *Queries) UpsertState(ctx context.Context, arg UpsertStateParams) error {
	_, err := q.exec(ctx, q.upsertStateStmt, upsertState, arg.Frontier, arg.CombinedAbi)
	return err
}
